[auth:slugs]
enabled = True
url     = http://127.0.0.1:8080/slugs/

[server]
hostname               = 0.0.0.0
port                   = 5696
certificate_path       = /data/server/server-cert.pem
key_path               = /data/server/server-privkey.pem
ca_path                = /data/server/ca-cert.pem
auth_suite             = TLS1.2
enable_tls_client_auth = False
logging_level          = INFO
database_path          = /data/db/pykmip.db
